[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = true
maxUploadSize = 1000
maxMessageSize = 1000

[client]
toolbarMode = "minimal"
showErrorDetails = true

[runner]
fastReruns = true

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#424242" 